config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  get "searches" => "searches#search"
  get "searches_post_day" => "searches#search_post_day"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,         dependent: :destroy
  has_many :favorites,     dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships,  class_name: "Relationship",
                                  foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                    dependent: :destroy

  has_many :following,                through: :active_relationships,
                                       source: :followed
  has_many :followers,                through: :passive_relationships,
                                       source: :follower


  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  #動かなくなってて草
  # def get_profile_image(width,height)
  #   (profile_image.attached?) ? profile_image.variant(resize_to_limit: [width, height]).processed : no_image.jpg.variant(resize_to_limit: [width, height]).processed
  # end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #_header検索フォームのデータ受け取り処理
  def self.looks(search_option, word)
    if    search_option == "perfect_match"               #完全一致
            @users = User.where("name LIKE ?", "#{word}")
    elsif search_option == "front_match"                 #前方一致
            @users = User.where("name LIKE ?", "#{word}%")
    elsif search_option == "back_match"                  #後方一致
            @users = User.where("name LIKE ?", "%#{word}")
    else #search_option == "partial_match"               #部分一致
            @users = User.where("name LIKE ?", "%#{word}%")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @time = Time.now
    @today =     Book.where(user_id: @user.id,
                         created_at: @time.in_time_zone.all_day)
  # これをリファクタリングしたい
    # @day1 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(1.days).all_day)
    # @day2 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(2.days).all_day)
    # @day3 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(3.days).all_day)
    # @day4 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(4.days).all_day)
    # @day5 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(5.days).all_day)
    # @day6 =      Book.where(user_id: @user.id,
    #                     created_at: @time.in_time_zone.ago(6.days).all_day)
  # 絶対間違ってる、これ過去の履歴作る時全部手書きすることになるやんけ。creaated_atでwhereする方法ないかな

  #リファクタリング案１<動的メソッド作成>
  #スッキリはしたけどこれだと「何日分のデータが欲しい」って時に書き直さないと検索できない
    6.times do |i|
      instance_variable_set("@day"+(i + 1).to_s,
                            Book.where(user_id: @user.id,
                                    created_at: @time.in_time_zone.ago((i + 1).days).all_day)
                            )
    end

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followers
    @users = User.find(params[:id]).followers
  end

  def following
    @users = User.find(params[:id]).following
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.active_relationships.count %></td>
        <td>フォロワー数<%= user.passive_relationships.count %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to "#{user.active_relationships.count}", following_user_path(user) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to "#{user.passive_relationships.count}", followers_user_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', relationship_path(user), method: :delete, class: 'btn btn-info' %>
    <% else %>
      <%= link_to 'フォローする', relationships_path(id: "#{user.id}"), method: :post, class: 'btn btn-success' %>
    <% end %>
  <% end %>
</div>

app/views/users/_search_post_day.html.erb
<h3>検索結果</h3>
<table class='table'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
<tbody>
      <tr>
        <td>
           <%= books.count %>
        </td>
      </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<%= render "follow", users: @users %>

app/views/users/following.html.erb
<h1>Follow Users</h1>
<%= render "follow", users: @users %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <%= render 'books/index',books: @books %>

<!--非同期検索機能-->
      <div class="container">
        <%= form_with url: searches_post_day_path, method: :get, local: false do |f| %>
          <div class="text-center">
            <%= f.date_field :post_day %>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <%= f.submit '検索' %>
          </div>
        <% end %>
        <div id="day_search"><!--js用render書き換え元スペース--></div>
      </div>
    </div>
  </div>
</div>