config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  get "searches" => "searches#search"
  get "searches_post_day" => "searches#search_post_day"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search_option, word)
    if    search_option == "perfect_match"               #完全一致
            @books = Book.where("title LIKE ?", "#{word}")
    elsif search_option == "front_match"                 #前方一致
            @books = Book.where("title LIKE ?", "#{word}%")
    elsif search_option == "back_match"                  #後方一致
            @books = Book.where("titlw LIKE ?", "%#{word}")
    else #search_option == "partial_match"               #部分一致
            @books = Book.where("title LIKE ?", "%#{word}%")
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comments.html.erb
    <!--コメント一覧-->
        <% book.book_comments.each do |book_comment| %>
          <div>
            <%= image_tag book_comment.user.get_profile_image(50,50) %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to 'Destroy', book_book_comment_path(book_comment.book.id,book_comment.id), class: "btn btn-danger", method: :delete, local: false %>
            <% end %>
            <br><%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
          </div>
        <% end %>
      <div>
    <!--コメントフォーム-->
        <%= form_with model: [book, comment], local: false do |f| %>
          <%= f.text_area :comment, rows: '5', class: 'form-control book_comment' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

app/views/books/_comments_func.html.erb
    <!--コメント一覧-->
      <div id="comments_func">
        <% book.book_comments.each do |book_comment| %>
          <div>
            <%= image_tag book_comment.user.get_profile_image(50,50) %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to 'Destroy', book_book_comment_path(book_comment.book.id,book_comment.id), class: "btn btn-danger", method: :delete, remote: true %>
            <% end %>
            <br><%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
          </div>
        <% end %>
      <div>
    <!--コメントフォーム-->
        <%= form_with model: [book, comment], local: false do |f| %>
          <%= f.text_area :comment, rows: '5', class: 'form-control book_comment' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
      </div>

app/views/books/_favorites.html.erb
<%= link_to book_favorites_path(book), id: "favorites#{book.id}", method: :post, remote: true do %>
  <i id='favcount', class="fas fa-heart"></i>
  <%= book.favorites.count %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
        <% if book.favorited_by?(current_user) %>
        <!--usersからのrenderだとbooks/って表記しないと読み込めない-->
          <%= render 'books/unfavorites', book: book %>
        <% else %>
          <%= render 'books/favorites',   book: book %>
        <% end %>
        </td>
        <td>コメント数<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_unfavorites.html.erb
<%= link_to book_favorites_path(book), id: "unfavorites#{book.id}", method: :delete, remote: true do %>
  <i class="fas fa-heart" style= "color:red;"></i>
  <span id='favcount', style= "color:red;"><%= book.favorites.count %></span>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
<!--サイドバー-->
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'form', book: @book_new %>
    </div>

<!--ページレイアウトとコンテンツ名-->
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		  <table class='table'>

    <!--投稿ユーザー情報と投稿情報-->
  		    <tr>
            <td><%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image(50,50) %><br>
    <!--問題の１行-->
              <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, @book %></td>
            <td><%= @book.body %></td>
    <!--Fav機能-->
            <td>
            <% if @book.favorited_by?(current_user) %>
              <%= render 'unfavorites', book: @book %>
            <% else %>
              <%= render 'favorites',   book: @book %>
            <% end %>
            </td>
    <!--コメント数-->
            <td id="comments_count">
              コメント数:<%= @book.book_comments.count %>
            </td>
    <!--投稿editリンク-->
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
<!--コメント一覧と機能-->
    <%= render 'comments_func', book: @book,comment: @comment %>
    </div>
  </div>
</div>